Website/Models/GameOfLifeModel.cs
using GameOfLife.Assets;

namespace Website.Models
{
    public class GameOfLifeModel
    {
        public GameOfLifeModel(CellType[][] grid, Game game)
        {
            Grid = grid;
            Game = game;
        }

        public GameOfLifeModel()
        {
            
        }
        
        public CellType[][] Grid { get; set; }
        public Game Game { get; set; }
    }
}

Website/Models/Schedule.cs
using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace Website.Models
{
    public class Schedule
    {
        [BsonId]
        public ObjectId Id { get; set; }
        public DayOfWeek DayOfWeek { get; set; }
        public bool EvenWeeks { get; set; }
        public string Task { get; set; }
    }
}

Website/Models/SudokuSolverModel.cs
namespace Website.Models
{
    public class SudokuSolverModel
    {
        public bool IsSolved { get; set; }
        public char[] Board { get; set; }
        public string ErrorMessage { get; set; }
    }
}

Website/Controllers/DailyProblemController.cs
using System.Linq;
using System.Web.Mvc;
using DailyCodingProblem;

namespace Website.Controllers
{
    public class DailyProblemController : Controller
    {
        public ActionResult Index(int? number)
        {
            if (number == null)
                return View();

            var problem = InterfaceImplementations
                .InstancesOf<IProblem>()
                .FirstOrDefault(e => e.Problem == number.Value);

            return problem == null 
                ? View() 
                : View(problem.Problem);
        }
    }
}

Website/Controllers/GameOfLifeController.cs
using System.Threading;
using System.Web.Mvc;
using GameOfLife.Assets;
using Website.Models;

namespace Website.Controllers
{
    public class GameOfLifeController : Controller
    {
        private Game _game;
        public ActionResult Index()
        {
            _game = new Game(10,10);
            _game.SetCell(5,5, CellType.Live);
            _game.SetCell(5,6, CellType.Live);
            _game.SetCell(5,7, CellType.Live);
            _game.SetCell(6,6, CellType.Live);
            _game.SetCell(4,6, CellType.Live);
            
            var model = new GameOfLifeModel(_game.GetGrid(), _game);
        
            return View(model);
            
        }

        [HttpPost]
        public ActionResult NextGeneration(GameOfLifeModel model)
        {
            model.Game.ComputeNextGeneration();
            model.Grid = model.Game.GetGrid();

            return Json(model.Grid);
        }
    }
}

Website/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Website.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Website/Controllers/RomanNumeralConverterController.cs
using System.Web.Mvc;
using CodingDojo.RomanNumbers;

namespace Website.Controllers
{
    public class RomanNumeralConverterController : Controller
    {
        private readonly RomanNumberConverter _converter;
        
        public RomanNumeralConverterController()
        {
            _converter = new RomanNumberConverter();
        }
        
        public ActionResult Index(string result)
        {
            return View(result);
        }

        [HttpPost]
        public ActionResult Convert(string romanNumeral)
        {
            var result = int.TryParse(romanNumeral, out var number) 
                ? _converter.ToRoman(number) 
                : _converter.ToInteger(romanNumeral).ToString();

            return View("Index", model: result);
        }
    }
}

Website/Controllers/SudokuSolverController.cs
using System.Linq;
using System.Web.Mvc;
using DailyCodingProblem.Problem054;
using Website.Extensions;
using Website.Models;

namespace Website.Controllers
{
    public class SudokuSolverController : Controller
    {
        public ActionResult Index(string errorMessage = null)
        {
            return View(new SudokuSolverModel()
            {
                Board = new char[81],
                ErrorMessage = errorMessage
            });
        }

        [HttpPost]
        public ActionResult SolveSudoku(char[] board)
        {
            var solver = new Problem054();
            var twoDimensionalBoard = board.To2DArray(9);

//            if (!BoardValidator.Validate(twoDimensionalBoard))
//            {
//                return RedirectToAction("Index", routeValues: "Not solveable.");
//            }
            
            var result = solver.SolveSudoku(twoDimensionalBoard);
            var model = new SudokuSolverModel()
            {
                IsSolved = result.IsSolved,
                Board = result.Board.Cast<char>().ToArray()
            };

            if (model.IsSolved)
            {
                return View("Index", model);
            }

            return RedirectToAction("Index", routeValues: "Not solveable.");
        }
    }
}

Website/Controllers/UnoController.cs
using System.Web.Mvc;

namespace Website.Controllers
{
    public class UnoController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Draw()
        {
            return null;
        }

        public ActionResult Play()
        {
            return null;
        }

        private void Evaluate()
        {
        }
    }
}

Website/Views/DailyProblem/Index.cshtml
@model DailyCodingProblem.IProblem

<h1>Problem @Model.Problem</h1>

Website/Views/GameOfLife/Index.cshtml
@using GameOfLife.Assets
@model Website.Models.GameOfLifeModel

@{
    ViewBag.Title = "Game of life";
}

<table>
    @foreach (var row in Model.Grid)
    {
        <tr>
            @foreach (var column in row)
            {
                <td style="background: @(column == CellType.Dead ? "red" : "green")">@column</td>
            }
        </tr>
    }
</table>
<input type="button" value="Next generation" class="nextGen" />

<script>
    $('.nextGen').on('click', function(){
        $.ajax({
            type: 'POST',
            url: '/gameoflife/nextgeneration',
            data: JSON.stringify({ grid: "@Model.Grid", game: "@Model.Game" }),
            contentType: 'application/json; charset=utf-8',
            dataType: 'json',
            success: function(msg) {
                alert(msg.d);
            }
        });
    });
</script>
<!-- TODO:
- Do javascript stuff here to automatically update table grid.
- Make inputs to decide grid size and starting point of dead/live cells.
- Make a start/stop button.
- Move everything to javascript, strip controller of any logic.
-->

Website/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Website/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    My Company Address
</address>

Website/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Website/Views/RomanNumeralConverter/Index.cshtml
@model string

<div>
    <form method="POST" action="RomanNumeralConverter/Convert">
        <input type="text" name="romanNumeral" placeholder="Enter number or roman numeral" />
        <input type="submit" value="Convert"/>
        
        @Html.DisplayForModel()
    </form>
</div>

Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Game of Life", "Index", "GameOfLife")</li>
                    <li>@Html.ActionLink("Sudoku solver", "Index", "SudokuSolver")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.2019 - My ASP.NET Application</p>
        </footer>
    </div>

    
    @RenderSection("scripts", required: false)
</body>
</html>

Website/Views/SudokuSolver/Index.cshtml
@model Website.Models.SudokuSolverModel

<form action="/SudokuSolver/SolveSudoku" method="post">
    @for (var i = 0; i < Model.Board.Length; i++)
    {
        if (i % 9 == 0)
        {
            <br/>
        }
        @Html.TextBoxFor(m => m.Board[i], new
        {
            @Value = char.IsDigit(Model.Board[i]) ? Model.Board[i] : '.', 
            @Style = "width: 40px; height: 40px; text-align: center;", 
            @Type = "number", 
            @Min = "1", 
            @Max = "9",
            @Step = "1", 
            @OnKeyPress = "return event.charCode >= 49 && event.charCode <= 57"
        })
        
    }
    <br/>
    @Html.DisplayFor(e => e.ErrorMessage)
    <br/>
    <input type="submit" value="Try solve"/>
</form>

<form action="/SudokuSolver/Index" method="post">
    <input type="submit" value="Reset"/>
</form>

Website/Views/Uno/Index.cshtml
@model dynamic

@{
    Layout = null;
}